<?php

return [

    // cbc
    'WBC',
    'RBC',
    'HGB,Blood',
    'HCT,Blood',
    'MCV',
    'MCH',
    'MCHC',
    'PLT',
    'RDW-CV',
    'NRBC%',
    'NRBC#',
    'NEUTROPHILS %',
    'LYMPHOCYTES %',
    'MONOCYTES %',
    'EOSINOPHILS %',
    'BASOPHILS %',
    'IMMATURE GRANULOCYTE %',
    'NEUTROPHILS #',
    'LYMPHOCYTES #',
    'MONOCYTES #',
    'EOSINOPHILS #',
    'BASOPHILS #',
    'IMMATURE GRANULOCYTE #',
    'NEUTROPHILS %(M)',
    'LYMPHOCYTES %(M)',
    'MONOCYTES %(M)',
    'EOSINOPHILS %(M)',
    'BASOPHILS %(M)',
    'MYELOCYTE %(M)',
    'NEUTROPHILS #(M)',
    'LYMPHOCYTES #(M)',
    'MONOCYTES #(M)',
    'EOSINOPHILS #(M)',
    'BASOPHILS #(M)',
    'IMMATURE GRANULOCYTE #(M)',
    'RBC MORPHOLOGY',
    'PLT (ESTM)',
    'PLT MORPHOLOGY',
    'ANISOCYTOSIS',
    'MACROCYTOSIS',
    'POIKILOCYTOSIS',
    'SCHISTOCYTES',
    'BURR CELLS',

    // chem
    'GLUCOSE,Blood',
    'SODIUM,Blood',
    'POTASSIUM,Blood',
    'CHLORIDE,Blood',
    'CARBON DIOXIDE,Blood',
    'UREA NITROGEN,Blood',
    'CREATININE,blood',
    'CALCIUM,Blood',
    'ANION GAP,blood',
    'EGFR CKD,blood',

    // LFT/CMP
    'PROTEIN,TOTAL,Blood',
    'ALBUMIN ,Blood',
    'BILIRUBIN,TOTAL,Blood',
    'BILIRUBIN,DIRECT,blood',
    'ALKP,Blood',
    'ALT,Blood',
    'AST,Blood',
    'MAGNESIUM,Blood',
    'PHOSPHORUS,Blood',

    // ABG
    'SODIUM,ISTAT',
    'POTASSIUM,ISTAT',
    'PH @ 37C',
    'PCO2 @ 37C',
    'TCO2',
    'PO2 @ 37C',
    'HCO3',
    'BASE EXCESS (BE)',
    'O2 SAT%',
    'FIO2',
];
