<?php

return [

    // cbc
    'WBC',
    'RBC',
    'HGB,Blood',
    'HCT,Blood',
    'MCV',
    'MCH',
    'MCHC',
    'PLT',
    'RDW-CV',
    'NRBC%',
    'NRBC#',
    'NEUTROPHILS %',
    'LYMPHOCYTES %',
    'MONOCYTES %',
    'EOSINOPHILS %',
    'BASOPHILS %',
    'IMMATURE GRANULOCYTE %',
    'NEUTROPHILS #',
    'LYMPHOCYTES #',
    'MONOCYTES #',
    'EOSINOPHILS #',
    'BASOPHILS #',
    'IMMATURE GRANULOCYTE #',
    'NEUTROPHILS %(M)',
    'LYMPHOCYTES %(M)',
    'MONOCYTES %(M)',
    'EOSINOPHILS %(M)',
    'BASOPHILS %(M)',
    'MYELOCYTE %(M)',
    'METAMYELOCYTE %(M)',
    'NEUTROPHILS #(M)',
    'LYMPHOCYTES #(M)',
    'MONOCYTES #(M)',
    'EOSINOPHILS #(M)',
    'BASOPHILS #(M)',
    'IMMATURE GRANULOCYTE #(M)',

    // CBC Morphology
    'RBC MORPHOLOGY',
    'PLT (ESTM)',
    'PLT MORPHOLOGY',
    'LARGE PLATELETS',
    'POLYCHROMASIA',
    'HYPOCHROMIA',
    'ANISOCYTOSIS',
    'MICROCYTOSIS',
    'MACROCYTOSIS',
    'POIKILOCYTOSIS',
    'SCHISTOCYTES',
    'SPHEROCYTES',
    'OVALOCYTES',
    'STOMATOCYTE',
    'BURR CELLS',
    'ACANTHOCYTES',
    'TEARDROP CELLS',

    // chem
    'GLUCOSE,Blood',
    'SODIUM,Blood',
    'POTASSIUM,Blood',
    'CHLORIDE,Blood',
    'CARBON DIOXIDE,Blood',
    'UREA NITROGEN,Blood',
    'CREATININE,blood',
    'CALCIUM,Blood',
    'ANION GAP,blood',
    'EGFR CKD,blood',

    // LFT/CMP
    'PROTEIN,TOTAL,Blood',
    'ALBUMIN ,Blood',
    'BILIRUBIN,TOTAL,Blood',
    'BILIRUBIN,DIRECT,blood',
    'ALKP,Blood',
    'ALT,Blood',
    'AST,Blood',
    'MAGNESIUM,Blood',
    'PHOSPHORUS,Blood',

    // ABG
    'SODIUM,ISTAT',
    'POTASSIUM,ISTAT',
    'PH @ 37C',
    'PCO2 @ 37C',
    'TCO2',
    'PO2 @ 37C',
    'HCO3',
    'BASE EXCESS (BE)',
    'O2 SAT%',
    'FIO2',

    // Coag
    'ANTI-Xa(UFH),BLOOD',
    'PROTHROMBIN TIME,blood',
    'INR,blood',
    'APTT',

    // Cardiac
    'BNP,BLOOD',
    'CK,Blood',
    'CKMB,blood',
    'CKMB INDEX,blood',
    'MYOGLOBIN,Blood',
    'TROPONIN-I,BLOOD',

    // UA
    'URINE GLUCOSE',
    'URINE PROTEIN',
    'URINE BILIRUBIN',
    'URINE UROBILINOGEN',
    'URINE PH',
    'URINE BLOOD',
    'URINE KETONES',
    'URINE NITRITE',
    'URINE LEUKOCYTE ESTERASE',
    'URINE CLARITY',
    'URINE SPECIFIC GRAVITY',
    'URINE COLOR',
    'RBC/HPF',
    'WBC/HPF',
    'URINE BACTERIA',
    'SQUAMOUS EPITHELIAL',
    'HYALINE CAST',
    'CALCIUM OXALATE',

];
